<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3sy2r9x\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3sy2r9x/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3sy2r9x.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3sy2r9x\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3sy2r9x\appAppKernelProdContainer([
    'container.build_hash' => '3sy2r9x',
    'container.build_id' => '0beea620',
    'container.build_time' => 1701345392,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3sy2r9x');
