<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD5FJtYm\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD5FJtYm/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerD5FJtYm.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerD5FJtYm\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerD5FJtYm\appAppKernelProdContainer([
    'container.build_hash' => 'D5FJtYm',
    'container.build_id' => '27850f6a',
    'container.build_time' => 1701333673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD5FJtYm');
