<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4BzejsH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4BzejsH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container4BzejsH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container4BzejsH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container4BzejsH\appAppKernelProdContainer([
    'container.build_hash' => '4BzejsH',
    'container.build_id' => '6565c9d4',
    'container.build_time' => 1701248807,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4BzejsH');
