<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.query.handler.paypal.identity.get_client_token' shared service.

return $this->services['ps_checkout.query.handler.paypal.identity.get_client_token'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\Identity\QueryHandler\GetClientTokenPayPalQueryHandler(($this->services['ps_checkout.event.dispatcher'] ?? $this->load('getPsCheckout_Event_DispatcherService.php')));
