<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxlnmiy\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxlnmiy/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUxlnmiy.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerUxlnmiy\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerUxlnmiy\appAppKernelProdContainer([
    'container.build_hash' => 'Uxlnmiy',
    'container.build_id' => '23d6b1d6',
    'container.build_time' => 1701248773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxlnmiy');
